In [1]:
import pandas as pd
path = "dataMissingValue.csv"
df = pd.read_csv(path)
df

  Name   School Level Blood Type   Age   Fav Fruit  Shoe Chart
0    A    High School         AB  15.0       apple        36.0
1    B    High School        NaN  17.0      banana        41.0
2    C    High School        NaN   NaN  watermelon         NaN
3    D    High School        NaN  16.0         NaN        38.0
4    E  Middle School          B  15.0      banana        37.0
5    F  Middle School        NaN  14.0      grapes         NaN
6    G  Middle School          O   NaN       mango        36.0
7    H    High School          A  16.0      papaya        39.0
8    I    High School        NaN  18.0         NaN        40.0
9    J  Middle School        NaN   NaN     avocado        35.0

In [2]:
df.isnull().sum()

Name            0
School Level    0
Blood Type      6
Age             3
Fav Fruit       2
Shoe Chart      2
dtype: int64

In [3]:
percent_missing = 100*df.isnull().mean()
percent_missing

Name             0.0
School Level     0.0
Blood Type      60.0
Age             30.0
Fav Fruit       20.0
Shoe Chart      20.0
dtype: float64

In [4]:
df.dropna(axis=0)

  Name   School Level Blood Type   Age Fav Fruit  Shoe Chart
0    A    High School         AB  15.0     apple        36.0
4    E  Middle School          B  15.0    banana        37.0
7    H    High School          A  16.0    papaya        39.0

In [5]:
df.dropna(axis=1)

  Name   School Level
0    A    High School
1    B    High School
2    C    High School
3    D    High School
4    E  Middle School
5    F  Middle School
6    G  Middle School
7    H    High School
8    I    High School
9    J  Middle School

In [6]:
df.dropna(thresh=5)

  Name   School Level Blood Type   Age Fav Fruit  Shoe Chart
0    A    High School         AB  15.0     apple        36.0
1    B    High School        NaN  17.0    banana        41.0
4    E  Middle School          B  15.0    banana        37.0
6    G  Middle School          O   NaN     mango        36.0
7    H    High School          A  16.0    papaya        39.0

In [7]:
df.dropna(subset=['Age'])

  Name   School Level Blood Type   Age Fav Fruit  Shoe Chart
0    A    High School         AB  15.0     apple        36.0
1    B    High School        NaN  17.0    banana        41.0
3    D    High School        NaN  16.0       NaN        38.0
4    E  Middle School          B  15.0    banana        37.0
5    F  Middle School        NaN  14.0    grapes         NaN
7    H    High School          A  16.0    papaya        39.0
8    I    High School        NaN  18.0       NaN        40.0

In [8]:
df_drop = df.drop(columns = 'Blood Type')
df_drop

  Name   School Level   Age   Fav Fruit  Shoe Chart
0    A    High School  15.0       apple        36.0
1    B    High School  17.0      banana        41.0
2    C    High School   NaN  watermelon         NaN
3    D    High School  16.0         NaN        38.0
4    E  Middle School  15.0      banana        37.0
5    F  Middle School  14.0      grapes         NaN
6    G  Middle School   NaN       mango        36.0
7    H    High School  16.0      papaya        39.0
8    I    High School  18.0         NaN        40.0
9    J  Middle School   NaN     avocado        35.0

In [9]:
df_filled = df_drop.copy()
df_filled['Age'] = df['Age'].fillna(df['Age'].mean())
df_filled

  Name   School Level        Age   Fav Fruit  Shoe Chart
0    A    High School  15.000000       apple        36.0
1    B    High School  17.000000      banana        41.0
2    C    High School  15.857143  watermelon         NaN
3    D    High School  16.000000         NaN        38.0
4    E  Middle School  15.000000      banana        37.0
5    F  Middle School  14.000000      grapes         NaN
6    G  Middle School  15.857143       mango        36.0
7    H    High School  16.000000      papaya        39.0
8    I    High School  18.000000         NaN        40.0
9    J  Middle School  15.857143     avocado        35.0

In [10]:
df_filled['Shoe Chart'] = df['Shoe Chart'].fillna(df['Shoe Chart'].median())
df_filled

  Name   School Level        Age   Fav Fruit  Shoe Chart
0    A    High School  15.000000       apple        36.0
1    B    High School  17.000000      banana        41.0
2    C    High School  15.857143  watermelon        37.5
3    D    High School  16.000000         NaN        38.0
4    E  Middle School  15.000000      banana        37.0
5    F  Middle School  14.000000      grapes        37.5
6    G  Middle School  15.857143       mango        36.0
7    H    High School  16.000000      papaya        39.0
8    I    High School  18.000000         NaN        40.0
9    J  Middle School  15.857143     avocado        35.0

In [11]:
df_filled['Fav Fruit'] = df['Fav Fruit'].fillna(df['Fav Fruit'].mode().iloc[0])
df_filled

  Name   School Level        Age   Fav Fruit  Shoe Chart
0    A    High School  15.000000       apple        36.0
1    B    High School  17.000000      banana        41.0
2    C    High School  15.857143  watermelon        37.5
3    D    High School  16.000000      banana        38.0
4    E  Middle School  15.000000      banana        37.0
5    F  Middle School  14.000000      grapes        37.5
6    G  Middle School  15.857143       mango        36.0
7    H    High School  16.000000      papaya        39.0
8    I    High School  18.000000      banana        40.0
9    J  Middle School  15.857143     avocado        35.0

In [12]:
df_filled2 = df_drop.copy()
df_filled2['Shoe Chart'] = df_filled2['Shoe Chart'].replace("", None).bfill()
df_filled2

  Name   School Level   Age   Fav Fruit  Shoe Chart
0    A    High School  15.0       apple        36.0
1    B    High School  17.0      banana        41.0
2    C    High School   NaN  watermelon        38.0
3    D    High School  16.0         NaN        38.0
4    E  Middle School  15.0      banana        37.0
5    F  Middle School  14.0      grapes        36.0
6    G  Middle School   NaN       mango        36.0
7    H    High School  16.0      papaya        39.0
8    I    High School  18.0         NaN        40.0
9    J  Middle School   NaN     avocado        35.0

In [13]:
df_filled2['Fav Fruit'] = df_filled2['Fav Fruit'].replace("", None).ffill()
df_filled2

  Name   School Level   Age   Fav Fruit  Shoe Chart
0    A    High School  15.0       apple        36.0
1    B    High School  17.0      banana        41.0
2    C    High School   NaN  watermelon        38.0
3    D    High School  16.0  watermelon        38.0
4    E  Middle School  15.0      banana        37.0
5    F  Middle School  14.0      grapes        36.0
6    G  Middle School   NaN       mango        36.0
7    H    High School  16.0      papaya        39.0
8    I    High School  18.0      papaya        40.0
9    J  Middle School   NaN     avocado        35.0

In [14]:
path = "weight-height_outlier.csv"
df2 = pd.read_csv(path)
df2

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [15]:
import seaborn as sns
sns.boxplot(df2['Height'])

ModuleNotFoundError: No module named 'seaborn'